global using System.Collections.Immutable;
global using laboratorio3.DataContracts;
global using laboratorio3.DataContracts.Serialization;
global using laboratorio3.Models;
global using laboratorio3.Presentation;
global using laboratorio3.Services.Caching;
global using laboratorio3.Services.Endpoints;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
